export enum tagTypes {
  user = "user",
  updateProfile = "updateProfile",
  resendVerificationCode = "resendVerificationCode",
  getMe = "getMe",

  // admin
  createCategoryApi = "createCategoryApi",
  getCategory = "getCategory",
  deleteCategory = "deleteCategory",
  editCategory = "editCategory",
  singleCategory = "singleCategory",
  createCourse = "createCourse",
  getCourses = "getCourses",
  deleteCourse = "deleteCourse",
  createModule = "createModule",
  getModules = "getModules",
  createModuleClass = "createModuleClass",
  deleteModule = "deleteModule",
  courseTargetAudience = "courseTargetAudience",
  getUsers = "getUsers",
  createInstructors = "createInstructors",
  createourMission = "createourMission",
  createServices = "createServices",
  createEbook = "createEbook",
  createFreeCourseRequest = "createFreeCourseRequest",
}

export const tagTypesList = [
  tagTypes.user,
  tagTypes.updateProfile,
  tagTypes.resendVerificationCode,
  tagTypes.getMe,

  // admin
  tagTypes.createCategoryApi,
  tagTypes.getCategory,
  tagTypes.deleteCategory,
  tagTypes.editCategory,
  tagTypes.singleCategory,
  tagTypes.createCourse,
  tagTypes.getCourses,
  tagTypes.deleteCourse,
  tagTypes.createModule,
  tagTypes.getModules,
  tagTypes.createModuleClass,
  tagTypes.deleteModule,
  tagTypes.courseTargetAudience,
  tagTypes.getUsers,
  tagTypes.createInstructors,
  tagTypes.createourMission,
  tagTypes.createServices,
  tagTypes.createEbook,
  tagTypes.createFreeCourseRequest,
];
